[package]
name = "proxy"
version = "0.1.2"
edition = "2021"
rust-version = "1.65"

[profile.release]
panic = 'abort'
strip = 'symbols'
lto = true

[dependencies]
mio = { version = "0.8", features = ["net", "os-poll"] }
